export enum OPERATION_NAMES {
  CHANNELS = 'CHANNELS',
  CLOSING_NOTES = 'CLOSING_NOTES',
  COMMENTS = 'COMMENTS',
  CONTACTS = 'CONTACTS',
  CONTACT_FIELDS = 'CONTACT_FIELDS',
  CONVERSATIONS = 'CONVERSATIONS',
  LIFECYCLE = 'LIFECYCLE',
  MESSAGES = 'MESSAGES',
  USER = 'USER',
  TAGS = 'TAGS',
}

export default OPERATION_NAMES;
