on:
  pull_request:
    types: [closed]
    branches:
      - 'dev'

name: Release Dev

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write

jobs:
  release_dev:
    uses: respond-io/shared-github-actions/.github/workflows/reusable-release-npm-pkgs.yaml@master
    with:
      target-branch: dev
      environment: dev
      block-release-on-audit-failure: false
    secrets:
      SLACK_PACKAGE_RELEASE_WORKFLOW_URL: ${{ secrets.SLACK_PACKAGE_RELEASE_WORKFLOW_URL }}